    name: "Workflow"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
            with:
                AUTO_ASSIGN: True
          - name: "TODO to Issue"
            uses: "alstr/todo-to-issue-action@v4.6.6"
            id: "todo"
